### ISSUE TITLE
Roadmap 2.0.0

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/raptorius-web-kit#17]
Так или иначе, для фиксации версии шаблона, нужно разобраться с волнующими меня вопросами:
### Common
- [x] Подумать на тему #16
- [x] Посмотреть свежим взглядом на код проекта и его архитектуру
- [x] Минимизировать количество зависимостей
- [x] Разобраться с тестированием и Travis CI
- [x] Подумать о PNG/SVG спрайтах
- [x] Как ни крути, но я не вижу смысла в BrowserSync — анализ вариантов и замена
### HTML
- [x] Добавить поддержку шаблонизатора Nunjucks
- [x] Поддержка puglint
- [x] Пересмотреть конфиг puglint
- [x] Вынести Pug-inheritance в отдельный модуль
### CSS
- [x] Поддержка stylelint
- [x] Пересмотреть конфиг stylelint
- [x] Обновить Normalize
- [x] Пересмотреть стили для всех препроцессоров
- [x] Подумать о добавлении PostCSS Flexbugs Fixes
### JavaScript
- [x] ~~Поддержка TypeScript из коробки (опционально скорее всего)~~
- [x] ~~Поддержка TSLint~~
- [x] XO, как чистый пакет
- [x] Пересмотреть конфиг XO
### Gulp
- [x] Пересмотреть обработку ошибок при сборке
- [x] Почистить задачи
- [x] Убрать линтеры из вотчеров, так как линтинг хоть и происходит инкрементально, но прерывает сборку из-за мелочей, вроде пропущенной точки с запятой или лишней строки. Полученный опыт при работе с исходниками VS Code говорит о том, что линтеры нужно включать при желании и перед финальной сборкой версии
- [x] Перенести конфигурации линтеров в отдельные JS-файлы
- [x] Пересмотреть загрузку задач Gulp
### Yellfy CLI
- [x] Переписать код с использованием TS
- [x] Дать возможность указать технологии в package.json (как альтернатива для аргументов `--sass` и т.д.)
  
  ``` json
  {
    "yellfy": {
      "css": "less",
      "html": "pug"
    }
  }
  ```
- [x]  Перенести шаблоны компонентов, модулей и прочего в этот репозиторий
### Документация
- [x] Установка и обновление
- [x] Структура
- [x] Технологии
- [x] Доступные задачи
- [x] Написание собственных задач
- [x] Настройки для Yellfy CLI
- [x] Как использовать Stylus?
- [x] Как использовать Sass?
- [x] Как использовать Nunjucks?
- [x] ~~Почему не Yeoman?~~
### Release
- [x] Зафиксировать все зависимости, используя `shrinkwrap`
- [ ] Обновить описание
  - [x] Ru
  - [ ] En
- [x] Добавить ссылки на соответствующие репозитории
- [x] Добавить в Readme информацию о рекомендуемых плагинах для редакторов, которые могут упростить работу с Yellfy (речь о линтерах)
- [ ] Написать пост на Canonium

**Comment by mrmlnc** [comment]
> Как ни крути, но я не вижу смысла в BrowserSync — анализ вариантов и замена

Посмотрев на доступные альтернативы, был выбран плагин `gulp-connect`. Вот несколько причин, по которым был сделан выбор:
1. Спонсируется JetBrains, а значит будет хоть какая-то поддержка.
2. В 5 раз меньше BrowserSync (5MB/1800 файлов против 25MB/3800 файлов).
3. Практически мгновенный запуск сервера.

**Comment by mrmlnc** [comment]
> Поддержка puglint

Добавлен Pug Lint. Однако, стоит ещё раз обратить внимание на обработку ошибок. С этим `done` творится что-то неладное. Нужно смотреть либо в сторону Plumber, либо копать в сторону `this.emit('end')`.

**Comment by mrmlnc** [comment]
Нужно подумать о внедрении [Nightmare](https://github.com/segmentio/nightmare). Очень просто интегрируется с Mocha.

**Comment by mrmlnc** [comment]
> Подумать о PNG/SVG спрайтах

Необходимо найти более лёгкую альтернативу для `gulp-svg-sprite`, так как этот плагин приносит в проект 3500 файлов, общим весом в 29Мб. Если такой нет, то напишем своё решение.

**Comment by mrmlnc** [comment]
Нужно что-то делать с тестами для Travis CI. 

Мне нравится текущее положение с тестами (HTML + собранный файл тестов) из-за того, что я могу открывать страницу с тестами в любом браузере и видеть результат их выполнения. В случае автоматизации тестов я буду ограничен лишь «Chrome», так как решения с WebdriverIO хотят денег 💸 или Java.

Проблема в том, что пакет `mocha-electron` не работает с HTML-файлами (не хочу добавлять ещё один JS-файл для `preload`), а его родственник `mochatron`, мягко говоря, поддерживается через отверстие и не умеет останавливаться по завершению тестов.

Хотелось бы иметь возможность выполнять тесты и на стороне CI. Возможно, следует сдаться и написать `preload`, либо написать свой `yellfy-mochatron`.

**Comment by mrmlnc** [comment]
Добавить поддержку описания задачи в `yellfy-loader`.

**Comment by mrmlnc** [comment]
Выделить документацию из README в директорию `docs`. Добавить в `yellfy-cli` фильтрацию файлов документации при развёртывании нового релиза.

**Comment by mrmlnc** [comment]
Не лениться и написать  эту чёртову документацию.

**Comment by mrmlnc** [comment]
Не так давно вышел TS@2.0.0, который, наконец-то, полностью покрывает `Object`. Нужно инвестировать в это направление для Yellfy. 

Обновить https://github.com/mrmlnc/tslint-config-xo

**Comment by mrmlnc** [comment]
Мои взгляды за последний месяц местами резко поменялись, поэтому нужно ещё раз всё перепроверить на их соответствие.

Однозначно нужно инвестировать в TS больше времени. Скорее всего Yellfy 2.0.0 будет дружить с ним. Подумать ещё раз о тестах, так как мне неуютно сейчас писать тесты, а без тестов мне неуютно вдвойне. Также необходимо пересмотреть систему компонентов и CLI. 

Желательно успеть до конца ноября, когда я начну всерьёз искать работу.

**Comment by mrmlnc** [comment]
Нам нужен новый итерационной план. Пожалуй, `2.0.0-restart`.

## Чего я хочу?

Я хочу использовать TS (пока не точно, но скорее всего). 

Я хочу, чтобы присутствовала настоящая компонентная структура:
- Компоненты
  - компонент
    - стили
    - скрипты
    - шаблоны

В текущей реализации меня не устраивает необходимость путешествия из директории в директорию и поиска нужного файла на проектах, где количество компонентов выше 50. Нужно хорошенько продумать это момент.

Теоретически я могу иметь лишь одну директорию `components`, которая содержит все кроме точки входа страниц, стилей и скриптов. Однако при этом количество поддиректорию вырастает в несколько раз, например, типографика или стека, как компонент.

Можно иметь директории: `components`, `styles`, `scripts` и `templates`, тогда изменения будут минимальными и логичными. Например, приложение может иметь много основных скриптов и при этом минимум компонентных (тоже самое со стилями). Но в этом случае мне нужно будет продумать систему вложений, чтобы она была относительно директории `app`, а не текущего файла.

Я хочу больше автоматизации.

**Comment by mrmlnc** [comment]
Итак, я почитал статейки, полистал репозитории и оценил некоторые проекты. Текущий исход моих мыслей таков:
1. Отдельная директория для компонентов.
2. Компонент имеет:
   - name.less
   - name.ts или js (пока не решил)
   - name.pug (условно, так как мы в процессе переезда на PostHTML + SugarML)
   - `images/sprite` — собирается в спрайт(SVG/PNG)
   - `images/*` — копируется в `build`
3. Сборщик ничего не знает о компонентах.
4. Наличие в сборке стилей или скриптов будет контролироваться из файла в корне директории компонентов. Возможно это будет два файла: один для скриптов и другой для стилей.
5. Скрипты (пока сложно сказать, так как нужно уточнить этот вопрос):
   - Если это TS, то автоматическая компиляция всех компонентов в JS и при сборке проекта будет конкатенация в один файл или подгружаемые модули в зависимости от размера проекта.
   - Если JS, то Babel (может быть Buble) + Rollup. Хотя Rollup порой тупит и падает из-за переполнения стека.
6. Шаблоны представляют собой либо миксины, либо живые файлы, подключаемые при необходимости.
7. Общие стили (фреймворк) будут в директории `styles` И будут значительно упрощены. Так, например, я собираюсь выбросить все модификаторы и оставить лишь самое необходимое. Больше всех пострадают таблицы и сетка.
8. Ядро скриптов будет жить в директории `scripts`.
9. Стили, скорее всего, будем дружить с БЭМ, либо продолжим использовать мою интерпретацию всего этого добра.

По компонентам у меня пока всё. В свободное время продолжу исследование по поводу сборки скриптов и организации кода.

**Comment by mrmlnc** [comment]
Пока выдалась свободная минутка:

Набрел вчера на `accord`, который представляет собой унифицированный интерфейс для работы с большим количеством популярных компилируемых языков и шаблонизаторов. Было бы круто дать возможность Yellfy менять ЯП и шаблонизатор в одну команду без генератора проектов, вроде yeoman. Например, замена CSS-препроцессора будет выполняться в виде команды:

```
$ yellfy switch scss 
```

Что подразумевает под собой:
- Клонирование репозитория `yellfy-styles-scss` в директорию `app/styles`
- Выполнение команды `npm rm -D less less-plugin-glob && npm i -D node-sass`
- Замена значения поля `yellfy.css` в `package.json`

Остальное на себя возьмёт этот пакет и логика переключения обработчика ошибок.

Нужно посмотреть на этот пакет более детально и оценить его полезность. Хотя, можно сделать тоже самое, просто передав в переменную нужный Gulp-плагин.

**Comment by mrmlnc** [comment]
Как ни крути, а вокруг JS крутится куда больше инструментов, чем у TS. Я вот думаю, что можно прикрутить Flow к JS и не париться. Однако, в случае использования TS мы можем забыть про Babel, чем сэкономим кучу времени не только при развёртывании Yellfy, но и при трансформирования кода.

В тоже время со стороны инструментов нас жмёт ESLint — как ни крути, но ему конкурентов в мире TS нет. Можно написать кучу правил для TSLint, но это на грани — столько времени у меня нет.

Для себя, конечно, приятнее работать с TS, но нужно понимать, что после меня проекты также будут кем-то поддерживаться. Хотя, в основном, я использую только базовые фишки TS и мой код практически эквивалентен JS. Также я могу написать простую вводную статью для быстрого ознакомления.

Как всегда, нужно подумать над проблемой и что-то решить к моменту начала работ над задачей скриптов.
