### ISSUE TITLE
Roadmap to 2.0.0-restart

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/raptorius-web-kit#27]
## Before

  * [ ] Close `2.0.0` milestone
  * [ ] Drop support Nunjucks

### Templates

  * [ ] `yellfy-pug-inheritance` ~~~(blocked by https://github.com/mrmlnc/yellfy-pug-inheritance/issues/18)~~~
  * [ ] PostHTML
    * [ ] `posthtml-sugarml` (need small/major refactoring)
    * [ ] `posthtml-extend`
    * [ ] `posthtml-include` (blocked by https://github.com/posthtml/posthtml-include/issues/14)
    * [ ] `posthtml-custom-elements`
    * [ ] `posthtml-expressions` ~~~(blocked by https://github.com/posthtml/posthtml-expressions/pull/32)~~~
    * [ ] `posthtml-content`
      * [ ] Markdown helper

### Styles

  * [ ] Update Normalize

### Images

  * [ ] `svg2sprite` ~~~(blocked by https://github.com/mrmlnc/svg2sprite/issues/1)~~~

### Common

  * [ ] `syncy` ~~~(blocked by https://github.com/mrmlnc/syncy/issues/8)~~~

**Comment by mrmlnc** [comment]
###  Временные метки для Assets

> Не знаю чем там пользуются некоторые клиенты, то у них кэш долго весит и не чистится (what?). Нужно рандомно добавлять ?123124124 к локальным CSS и JS файлам.

### Интеграция с VS Code 

> Так как VS Code предлагает некоторые плюшки, нужно провести интеграцию: рекомендация плагинов, задачи и отладчик.

### Пропуск линтеров

> Иногда, когда ты запускаешь проект, линтеры ругаются на пропущенную строку, а тебе нужно всего лишь исправить `padding`, чтобы показать клиенту. Нужно предоставить опцию для исключения линтеров из процесса сборки.

### Падения из-за postcss

> Изредка бывает, что файл сохраняется без точки с запятой в конце свойства, что вызывает ошибку у postcss и Yellfy падает.

### Решение вопроса с Travis CI (electron-mocha, mochatron, Nightmare и т.д.)

Нужно что-то делать с тестами для Travis CI.

> Мне нравится текущее положение с тестами (HTML + собранный файл тестов) из-за того, что я могу открывать страницу с тестами в любом браузере и видеть результат их выполнения. В случае автоматизации тестов я буду ограничен лишь «Chrome», так как решения с WebdriverIO хотят денег 💸 или Java.

> Проблема в том, что пакет `mocha-electron` не работает с HTML-файлами (не хочу добавлять ещё один JS-файл для `preload`), а его родственник `mochatron`, мягко говоря, поддерживается через отверстие и не умеет останавливаться по завершению тестов.

> Хотелось бы иметь возможность выполнять тесты и на стороне CI. Возможно, следует сдаться и написать preload, либо написать свой `yellfy-mochatron`.

> Mochatron обновился — нужно проверить его пригодность.
